[package]
name = "fediverse-observer"
version = "0.1.0"
edition = "2018"
license = " AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexopt = "0.1"
anyhow = "1"
tokio = { version = "1", features = [ "full" ] }
sloggers = "2"
slog = "2"
