[package]
name = "fediverse-observer"
version = "0.1.0"
edition = "2018"
license = " AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chrono = "0.4"
fastrand = "1"
json = "0.12"
lexopt = "0.1"
reqwest = { version = "0.11", features = [ "gzip", "brotli", "deflate", "json" ] }
rusqlite = { version = "0.26", features = [ "chrono" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
slog = "2"
slog-journald = "2"
tokio = { version = "1", features = [ "full" ] }
url = "2"
