---
- hosts: production
  become: yes

  tasks:
  - name: Deploy favicon.ico.
    copy:
      src: "favicon.ico"
      dest: /var/lib/fedicrawler/www/
      owner: fedicrawler
      group: fedicrawler
      mode: "u=rw,go=r"

  - name: Deploy index.html.
    copy:
      src: "{{ item.src }}"
      dest: /var/lib/fedicrawler/www/
      owner: fedicrawler
      group: fedicrawler
      mode: "u=rw,go=r"
    with_items:
      - { src: "../index.html" }
      - { src: "../index.html.gz" }

  - name: Ensure there is a symlink from www/{nodes,instances}.json to instances.json.
    file:
      src: "/var/lib/fedicrawler/instances.json"
      dest: "/var/lib/fedicrawler/www/{{ item.name }}"
      state: link
      # Create it even if the target file doens't exist.
      force: yes
    with_items:
      - { name: "nodes.json" }
      - { name: "instances.json" }

  - name: Ensure there is a symlink from www/{nodes,instances}.json.gz to instances.json.gz.
    file:
      src: "/var/lib/fedicrawler/instances.json.gz"
      dest: "/var/lib/fedicrawler/www/{{ item.name }}"
      state: link
      # Create it even if the target file doens't exist.
      force: yes
    with_items:
      - { name: "nodes.json.gz" }
      - { name: "instances.json.gz" }

  - name: Check if systemd service already exists.
    stat:
      path: /etc/systemd/system/minoru-fediverse-crawler.service
    register: systemd_service_file

  - name: Check if systemd service file should be changed.
    become: yes
    copy:
      src: minoru-fediverse-crawler.service
      dest: /etc/systemd/system/
      mode: "u=rw,go=r"
    check_mode: yes
    register: systemd_service

  - name: Check if crawler needs to be re-deployed.
    copy:
      src: ../target/release/minoru-fediverse-crawler
      dest: /var/lib/fedicrawler/
      owner: fedicrawler
      group: fedicrawler
      # Security precaution: the user can't overwrite the binary.
      mode: "u=rx,go="
    check_mode: yes
    register: crawler

  - name: Stop systemd service.
    become: yes
    when: systemd_service_file.stat.exists and (systemd_service.changed or crawler.changed)
    service:
      name: minoru-fediverse-crawler
      state: stopped

  - name: Ensure systemd service file exists.
    become: yes
    when: systemd_service.changed
    copy:
      src: minoru-fediverse-crawler.service
      dest: /etc/systemd/system/
      mode: "u=rw,go=r"

  - name: Deploy the crawler.
    when: crawler.changed
    copy:
      src: ../target/release/minoru-fediverse-crawler
      dest: /var/lib/fedicrawler/
      owner: fedicrawler
      group: fedicrawler
      # Security precaution: the user can't overwrite the binary.
      mode: "u=rx,go="

  - name: Start systemd service.
    become: yes
    service:
      daemon_reload: yes
      name: minoru-fediverse-crawler
      state: started
      enabled: yes
