name: "Build and test"

on: [ push, pull_request ]

jobs:
  build_and_test:
    name: "Build and test"
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/cache
            ~/.cargo/registry/index

      - name: "Install project's dependencies"
        run: sudo apt-get update && sudo apt-get install --assume-yes libsystemd-dev

      - name: "cargo check"
        run: cargo check

      - name: "cargo clippy"
        run: cargo clippy --all-features

      - name: "cargo build"
        run: cargo build

      - name: "cargo test"
        run: cargo test
